baseURL = 'https://pjpscriv.co.nz/'
languageCode = 'en-us'
title = 'Peter Scriven'

defaultContentLanguage = "en"
[languages]
  [languages.en]
    languageName = "English"
    contentDir = "content/en"
    weight = 1
  
  [languages.fr]
    languageName = "Fran√ßais"
    contentDir = "content/fr"
    weight = 2

[markup]
  [markup.highlight]
    noClasses = false

[mediaTypes]
  [mediaTypes."application/rss+xml"]
    suffixes = ["xml"]

[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss+xml"
    baseName = "index"

  [outputFormats.feed]
    mediaType = "application/rss+xml"
    baseName = "feed"
    isPlainText = false
    rel = "alternate"

[outputs]
  home = ["HTML", "RSS", "feed"]
  section = ["HTML", "RSS", "feed"]
